[package]
name = "waca"
version = "0.1.0"
edition = "2021"

[dependencies]
cana = { path = "../cana" }
clap = { version = "4.5.8", features = ["derive"] }
lz4_flex = "0.11.3"
pollster = "0.3.0"
wasmer = "4.3.2"
wasmer-types = "4.3.2"
wgpu = "0.20.1"
winit = "0.30.3"
