[package]
name = "taca"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.1"
log = "0.4.20"
pollster = "0.3.0"
wasmtime = "15.0.1"
wgpu = "0.18.0"
winit = "0.28.7"
