[package]
name = "taca"
description = "A wasm runtime for multimedia apps and more"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
wasmer = "3.2.1"
wasmer-types = "3.2.1"
wgpu = "0.16.0"
wgpu-native = { git = "https://github.com/gfx-rs/wgpu-native.git", tag = "v0.16.0.1" }
winit = "0.28.3"
