package taca:core@0.0.1;

interface app {
    use key.{event as key-event};
    use task.{task};

    update: func(event: event);

    variant event {
        none,

        start,

        // Time delta in seconds.
        frame(f32),

        key(key-event),

        task-done(borrow<task>),

        tasks-all-done,
    }
}

interface archive {
    get-bytes: func(name: string) -> option<list<u8>>;
    get-text: func(name: string) -> option<string>;
}

interface console {
    print: func(text: string);
}

interface key {
    enum code {
        none,
        arrow-up,
        arrow-down,
        arrow-left,
        arrow-right,
        space,
        escape,
    }

    record event {
        code: code,
        pressed: bool,
    }
}

interface storage {
    use task.{task};

    // resource request {
    //     access: func() -> option<store>;
    //     task: func() -> option<task>;
    // }

    resource store {
        // TODO get-info: func(name: string) -> info; // struct

        get-bytes: func(name: string) -> bytes;
        get-text: func(name: string) -> text;

        // TODO Append option?

        set-bytes: func(name: string, value: list<u8>) -> task;
        set-text: func(name: string, value: string) -> task;
    }

    // record info { changed_at, ... }

    resource bytes {
        take: func() -> option<list<u8>>;
        task: func() -> option<task>;
    }

    resource text {
        take: func() -> option<string>;
        task: func() -> option<task>;
    }

    // Access the storage dedicated to this app.
    access: func() -> store;

    // Request access to the storage of a different app.
    // request: func(owner: string, app: string) -> request;
}

interface task {
    resource task {
        done: func() -> bool;
        failed: func() -> bool;
    }
}

world taca {
    export app;
    import archive;
    import console;
    import key;
    import storage;
}
