local common = @record{}

local d = require "./draw.nelua"
local t = require "taca"

local common.Uniforms = @record{
  aspect: [2]float32,
  pad: [2]float32,
}

local common.Game = @record{
  back: d.TextureBindings,
  blitter: d.Blitter,
  gem: d.TextureBindings,
  init_finished: boolean,
  middle: d.TextureBindings,
  player: d.TextureBindings,
  tile_map: vector(d.Blit),
  tiles: d.TextureBindings,
  uniforms: common.Uniforms,
  uniforms_buffer: t.Buffer,
}

return common
