[package]
name = "taca"
version = "0.1.0"
edition = "2024"

# I want this to apply just to wasm-pack, but how to do that?
[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true
opt-level = "s"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
blake3 = "1.8.2"
clap = { version = "4.5.38", features = ["derive"] }
directories = "6.0.0"
ed25519-dalek = { version = "2.1.1", features = ["digest", "rand_core"] }
env_logger = "0.11.8"
jiff = { version = "0.2.14", features = ["serde"] }
log = "0.4.27"
pollster = "0.4.0"
# Old rand because conflict, from wasmtime-wasi > cap-rand > rand
rand = "0.8.5"
rusqlite = "0.36.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_rusqlite = "0.39.0"
sha2 = "0.10.9"
tempfile = "3.20.0"
wasmtime = "33.0.0"
wasmtime-wasi = "33.0.0"
wgpu = "25.0.2"
winit = "0.30.11"
zip = "4.0.0"
