[package]
name = "taca"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
ed25519-dalek = { version = "2.1.1", features = ["digest", "rand_core"] }
env_logger = "0.11.8"
pollster = "0.4.0"
# Old rand because conflict, from wasmtime-wasi > cap-rand > rand
rand = "0.8.5"
sha2 = "0.10.9"
wasmtime = "33.0.0"
wasmtime-wasi = "33.0.0"
wgpu = "25.0.2"
winit = "0.30.11"
zip = "4.0.0"
