// Copied from wgpu-native.
// TODO Work out how to use wgpu-native and wgpu-rs in same app?

pub type WGPUPresentMode = u32;
pub const WGPUPresentMode_Immediate: WGPUPresentMode = 0x00000000;
pub const WGPUPresentMode_Mailbox: WGPUPresentMode = 0x00000001;
pub const WGPUPresentMode_Fifo: WGPUPresentMode = 0x00000002;

pub type WGPUTextureFormat = u32;
#[allow(dead_code)]
pub const WGPUTextureFormat_Undefined: WGPUTextureFormat = 0;
pub const WGPUTextureFormat_R8Unorm: WGPUTextureFormat = 1;
pub const WGPUTextureFormat_R8Snorm: WGPUTextureFormat = 2;
pub const WGPUTextureFormat_R8Uint: WGPUTextureFormat = 3;
pub const WGPUTextureFormat_R8Sint: WGPUTextureFormat = 4;
pub const WGPUTextureFormat_R16Uint: WGPUTextureFormat = 5;
pub const WGPUTextureFormat_R16Sint: WGPUTextureFormat = 6;
pub const WGPUTextureFormat_R16Float: WGPUTextureFormat = 7;
pub const WGPUTextureFormat_RG8Unorm: WGPUTextureFormat = 8;
pub const WGPUTextureFormat_RG8Snorm: WGPUTextureFormat = 9;
pub const WGPUTextureFormat_RG8Uint: WGPUTextureFormat = 10;
pub const WGPUTextureFormat_RG8Sint: WGPUTextureFormat = 11;
pub const WGPUTextureFormat_R32Float: WGPUTextureFormat = 12;
pub const WGPUTextureFormat_R32Uint: WGPUTextureFormat = 13;
pub const WGPUTextureFormat_R32Sint: WGPUTextureFormat = 14;
pub const WGPUTextureFormat_RG16Uint: WGPUTextureFormat = 15;
pub const WGPUTextureFormat_RG16Sint: WGPUTextureFormat = 16;
pub const WGPUTextureFormat_RG16Float: WGPUTextureFormat = 17;
pub const WGPUTextureFormat_RGBA8Unorm: WGPUTextureFormat = 18;
pub const WGPUTextureFormat_RGBA8UnormSrgb: WGPUTextureFormat = 19;
pub const WGPUTextureFormat_RGBA8Snorm: WGPUTextureFormat = 20;
pub const WGPUTextureFormat_RGBA8Uint: WGPUTextureFormat = 21;
pub const WGPUTextureFormat_RGBA8Sint: WGPUTextureFormat = 22;
pub const WGPUTextureFormat_BGRA8Unorm: WGPUTextureFormat = 23;
pub const WGPUTextureFormat_BGRA8UnormSrgb: WGPUTextureFormat = 24;
pub const WGPUTextureFormat_RGB10A2Unorm: WGPUTextureFormat = 25;
pub const WGPUTextureFormat_RG11B10Ufloat: WGPUTextureFormat = 26;
pub const WGPUTextureFormat_RGB9E5Ufloat: WGPUTextureFormat = 27;
pub const WGPUTextureFormat_RG32Float: WGPUTextureFormat = 28;
pub const WGPUTextureFormat_RG32Uint: WGPUTextureFormat = 29;
pub const WGPUTextureFormat_RG32Sint: WGPUTextureFormat = 30;
pub const WGPUTextureFormat_RGBA16Uint: WGPUTextureFormat = 31;
pub const WGPUTextureFormat_RGBA16Sint: WGPUTextureFormat = 32;
pub const WGPUTextureFormat_RGBA16Float: WGPUTextureFormat = 33;
pub const WGPUTextureFormat_RGBA32Float: WGPUTextureFormat = 34;
pub const WGPUTextureFormat_RGBA32Uint: WGPUTextureFormat = 35;
pub const WGPUTextureFormat_RGBA32Sint: WGPUTextureFormat = 36;
pub const WGPUTextureFormat_Stencil8: WGPUTextureFormat = 37;
pub const WGPUTextureFormat_Depth16Unorm: WGPUTextureFormat = 38;
pub const WGPUTextureFormat_Depth24Plus: WGPUTextureFormat = 39;
pub const WGPUTextureFormat_Depth24PlusStencil8: WGPUTextureFormat = 40;
pub const WGPUTextureFormat_Depth32Float: WGPUTextureFormat = 41;
pub const WGPUTextureFormat_Depth32FloatStencil8: WGPUTextureFormat = 42;
pub const WGPUTextureFormat_BC1RGBAUnorm: WGPUTextureFormat = 43;
pub const WGPUTextureFormat_BC1RGBAUnormSrgb: WGPUTextureFormat = 44;
pub const WGPUTextureFormat_BC2RGBAUnorm: WGPUTextureFormat = 45;
pub const WGPUTextureFormat_BC2RGBAUnormSrgb: WGPUTextureFormat = 46;
pub const WGPUTextureFormat_BC3RGBAUnorm: WGPUTextureFormat = 47;
pub const WGPUTextureFormat_BC3RGBAUnormSrgb: WGPUTextureFormat = 48;
pub const WGPUTextureFormat_BC4RUnorm: WGPUTextureFormat = 49;
pub const WGPUTextureFormat_BC4RSnorm: WGPUTextureFormat = 50;
pub const WGPUTextureFormat_BC5RGUnorm: WGPUTextureFormat = 51;
pub const WGPUTextureFormat_BC5RGSnorm: WGPUTextureFormat = 52;
pub const WGPUTextureFormat_BC6HRGBUfloat: WGPUTextureFormat = 53;
pub const WGPUTextureFormat_BC6HRGBFloat: WGPUTextureFormat = 54;
pub const WGPUTextureFormat_BC7RGBAUnorm: WGPUTextureFormat = 55;
pub const WGPUTextureFormat_BC7RGBAUnormSrgb: WGPUTextureFormat = 56;
pub const WGPUTextureFormat_ETC2RGB8Unorm: WGPUTextureFormat = 57;
pub const WGPUTextureFormat_ETC2RGB8UnormSrgb: WGPUTextureFormat = 58;
pub const WGPUTextureFormat_ETC2RGB8A1Unorm: WGPUTextureFormat = 59;
pub const WGPUTextureFormat_ETC2RGB8A1UnormSrgb: WGPUTextureFormat = 60;
pub const WGPUTextureFormat_ETC2RGBA8Unorm: WGPUTextureFormat = 61;
pub const WGPUTextureFormat_ETC2RGBA8UnormSrgb: WGPUTextureFormat = 62;
pub const WGPUTextureFormat_EACR11Unorm: WGPUTextureFormat = 63;
pub const WGPUTextureFormat_EACR11Snorm: WGPUTextureFormat = 64;
pub const WGPUTextureFormat_EACRG11Unorm: WGPUTextureFormat = 65;
pub const WGPUTextureFormat_EACRG11Snorm: WGPUTextureFormat = 66;
pub const WGPUTextureFormat_ASTC4x4Unorm: WGPUTextureFormat = 67;
pub const WGPUTextureFormat_ASTC4x4UnormSrgb: WGPUTextureFormat = 68;
pub const WGPUTextureFormat_ASTC5x4Unorm: WGPUTextureFormat = 69;
pub const WGPUTextureFormat_ASTC5x4UnormSrgb: WGPUTextureFormat = 70;
pub const WGPUTextureFormat_ASTC5x5Unorm: WGPUTextureFormat = 71;
pub const WGPUTextureFormat_ASTC5x5UnormSrgb: WGPUTextureFormat = 72;
pub const WGPUTextureFormat_ASTC6x5Unorm: WGPUTextureFormat = 73;
pub const WGPUTextureFormat_ASTC6x5UnormSrgb: WGPUTextureFormat = 74;
pub const WGPUTextureFormat_ASTC6x6Unorm: WGPUTextureFormat = 75;
pub const WGPUTextureFormat_ASTC6x6UnormSrgb: WGPUTextureFormat = 76;
pub const WGPUTextureFormat_ASTC8x5Unorm: WGPUTextureFormat = 77;
pub const WGPUTextureFormat_ASTC8x5UnormSrgb: WGPUTextureFormat = 78;
pub const WGPUTextureFormat_ASTC8x6Unorm: WGPUTextureFormat = 79;
pub const WGPUTextureFormat_ASTC8x6UnormSrgb: WGPUTextureFormat = 80;
pub const WGPUTextureFormat_ASTC8x8Unorm: WGPUTextureFormat = 81;
pub const WGPUTextureFormat_ASTC8x8UnormSrgb: WGPUTextureFormat = 82;
pub const WGPUTextureFormat_ASTC10x5Unorm: WGPUTextureFormat = 83;
pub const WGPUTextureFormat_ASTC10x5UnormSrgb: WGPUTextureFormat = 84;
pub const WGPUTextureFormat_ASTC10x6Unorm: WGPUTextureFormat = 85;
pub const WGPUTextureFormat_ASTC10x6UnormSrgb: WGPUTextureFormat = 86;
pub const WGPUTextureFormat_ASTC10x8Unorm: WGPUTextureFormat = 87;
pub const WGPUTextureFormat_ASTC10x8UnormSrgb: WGPUTextureFormat = 88;
pub const WGPUTextureFormat_ASTC10x10Unorm: WGPUTextureFormat = 89;
pub const WGPUTextureFormat_ASTC10x10UnormSrgb: WGPUTextureFormat = 90;
pub const WGPUTextureFormat_ASTC12x10Unorm: WGPUTextureFormat = 91;
pub const WGPUTextureFormat_ASTC12x10UnormSrgb: WGPUTextureFormat = 92;
pub const WGPUTextureFormat_ASTC12x12Unorm: WGPUTextureFormat = 93;
pub const WGPUTextureFormat_ASTC12x12UnormSrgb: WGPUTextureFormat = 94;

pub type WGPUTextureUsage = u32;
pub const WGPUTextureUsage_None: WGPUTextureUsage = 0x00000000;
pub const WGPUTextureUsage_CopySrc: WGPUTextureUsage = 0x00000001;
pub const WGPUTextureUsage_CopyDst: WGPUTextureUsage = 0x00000002;
pub const WGPUTextureUsage_TextureBinding: WGPUTextureUsage = 0x00000004;
pub const WGPUTextureUsage_StorageBinding: WGPUTextureUsage = 0x00000008;
pub const WGPUTextureUsage_RenderAttachment: WGPUTextureUsage = 0x00000010;

#[rustfmt::skip]
pub fn map_texture_format(value: WGPUTextureFormat) -> Option<wgpu::TextureFormat> {
    use wgpu::{AstcBlock, AstcChannel};
    match value {
        WGPUTextureFormat_R8Unorm => Some(wgpu::TextureFormat::R8Unorm),
        WGPUTextureFormat_R8Snorm => Some(wgpu::TextureFormat::R8Snorm),
        WGPUTextureFormat_R8Uint => Some(wgpu::TextureFormat::R8Uint),
        WGPUTextureFormat_R8Sint => Some(wgpu::TextureFormat::R8Sint),
        WGPUTextureFormat_R16Uint => Some(wgpu::TextureFormat::R16Uint),
        WGPUTextureFormat_R16Sint => Some(wgpu::TextureFormat::R16Sint),
        WGPUTextureFormat_R16Float => Some(wgpu::TextureFormat::R16Float),
        WGPUTextureFormat_RG8Unorm => Some(wgpu::TextureFormat::Rg8Unorm),
        WGPUTextureFormat_RG8Snorm => Some(wgpu::TextureFormat::Rg8Snorm),
        WGPUTextureFormat_RG8Uint => Some(wgpu::TextureFormat::Rg8Uint),
        WGPUTextureFormat_RG8Sint => Some(wgpu::TextureFormat::Rg8Sint),
        WGPUTextureFormat_R32Float => Some(wgpu::TextureFormat::R32Float),
        WGPUTextureFormat_R32Uint => Some(wgpu::TextureFormat::R32Uint),
        WGPUTextureFormat_R32Sint => Some(wgpu::TextureFormat::R32Sint),
        WGPUTextureFormat_RG16Uint => Some(wgpu::TextureFormat::Rg16Uint),
        WGPUTextureFormat_RG16Sint => Some(wgpu::TextureFormat::Rg16Sint),
        WGPUTextureFormat_RG16Float => Some(wgpu::TextureFormat::Rg16Float),
        WGPUTextureFormat_RGBA8Unorm => Some(wgpu::TextureFormat::Rgba8Unorm),
        WGPUTextureFormat_RGBA8UnormSrgb => Some(wgpu::TextureFormat::Rgba8UnormSrgb),
        WGPUTextureFormat_RGBA8Snorm => Some(wgpu::TextureFormat::Rgba8Snorm),
        WGPUTextureFormat_RGBA8Uint => Some(wgpu::TextureFormat::Rgba8Uint),
        WGPUTextureFormat_RGBA8Sint => Some(wgpu::TextureFormat::Rgba8Sint),
        WGPUTextureFormat_BGRA8Unorm => Some(wgpu::TextureFormat::Bgra8Unorm),
        WGPUTextureFormat_BGRA8UnormSrgb => Some(wgpu::TextureFormat::Bgra8UnormSrgb),
        WGPUTextureFormat_RGB10A2Unorm => Some(wgpu::TextureFormat::Rgb10a2Unorm),
        WGPUTextureFormat_RG11B10Ufloat => Some(wgpu::TextureFormat::Rg11b10Float),
        WGPUTextureFormat_RGB9E5Ufloat => Some(wgpu::TextureFormat::Rgb9e5Ufloat),
        WGPUTextureFormat_RG32Float => Some(wgpu::TextureFormat::Rg32Float),
        WGPUTextureFormat_RG32Uint => Some(wgpu::TextureFormat::Rg32Uint),
        WGPUTextureFormat_RG32Sint => Some(wgpu::TextureFormat::Rg32Sint),
        WGPUTextureFormat_RGBA16Uint => Some(wgpu::TextureFormat::Rgba16Uint),
        WGPUTextureFormat_RGBA16Sint => Some(wgpu::TextureFormat::Rgba16Sint),
        WGPUTextureFormat_RGBA16Float => Some(wgpu::TextureFormat::Rgba16Float),
        WGPUTextureFormat_RGBA32Float => Some(wgpu::TextureFormat::Rgba32Float),
        WGPUTextureFormat_RGBA32Uint => Some(wgpu::TextureFormat::Rgba32Uint),
        WGPUTextureFormat_RGBA32Sint => Some(wgpu::TextureFormat::Rgba32Sint),
        WGPUTextureFormat_Stencil8 => Some(wgpu::TextureFormat::Stencil8),
        WGPUTextureFormat_Depth16Unorm => Some(wgpu::TextureFormat::Depth16Unorm),
        WGPUTextureFormat_Depth24Plus => Some(wgpu::TextureFormat::Depth24Plus),
        WGPUTextureFormat_Depth24PlusStencil8 => Some(wgpu::TextureFormat::Depth24PlusStencil8),
        WGPUTextureFormat_Depth32Float => Some(wgpu::TextureFormat::Depth32Float),
        WGPUTextureFormat_Depth32FloatStencil8 => Some(wgpu::TextureFormat::Depth32FloatStencil8),
        WGPUTextureFormat_BC1RGBAUnorm => Some(wgpu::TextureFormat::Bc1RgbaUnorm),
        WGPUTextureFormat_BC1RGBAUnormSrgb => Some(wgpu::TextureFormat::Bc1RgbaUnormSrgb),
        WGPUTextureFormat_BC2RGBAUnorm => Some(wgpu::TextureFormat::Bc2RgbaUnorm),
        WGPUTextureFormat_BC2RGBAUnormSrgb => Some(wgpu::TextureFormat::Bc2RgbaUnormSrgb),
        WGPUTextureFormat_BC3RGBAUnorm => Some(wgpu::TextureFormat::Bc3RgbaUnorm),
        WGPUTextureFormat_BC3RGBAUnormSrgb => Some(wgpu::TextureFormat::Bc3RgbaUnormSrgb),
        WGPUTextureFormat_BC4RUnorm => Some(wgpu::TextureFormat::Bc4RUnorm),
        WGPUTextureFormat_BC4RSnorm => Some(wgpu::TextureFormat::Bc4RSnorm),
        WGPUTextureFormat_BC5RGUnorm => Some(wgpu::TextureFormat::Bc5RgUnorm),
        WGPUTextureFormat_BC5RGSnorm => Some(wgpu::TextureFormat::Bc5RgSnorm),
        WGPUTextureFormat_BC6HRGBUfloat => Some(wgpu::TextureFormat::Bc6hRgbUfloat),
        WGPUTextureFormat_BC6HRGBFloat => Some(wgpu::TextureFormat::Bc6hRgbFloat),
        WGPUTextureFormat_BC7RGBAUnorm => Some(wgpu::TextureFormat::Bc7RgbaUnorm),
        WGPUTextureFormat_BC7RGBAUnormSrgb => Some(wgpu::TextureFormat::Bc7RgbaUnormSrgb),
        WGPUTextureFormat_ETC2RGB8Unorm => Some(wgpu::TextureFormat::Etc2Rgb8Unorm),
        WGPUTextureFormat_ETC2RGB8UnormSrgb => Some(wgpu::TextureFormat::Etc2Rgb8UnormSrgb),
        WGPUTextureFormat_ETC2RGB8A1Unorm => Some(wgpu::TextureFormat::Etc2Rgb8A1Unorm),
        WGPUTextureFormat_ETC2RGB8A1UnormSrgb => Some(wgpu::TextureFormat::Etc2Rgb8A1UnormSrgb),
        WGPUTextureFormat_ETC2RGBA8Unorm => Some(wgpu::TextureFormat::Etc2Rgba8Unorm),
        WGPUTextureFormat_ETC2RGBA8UnormSrgb => Some(wgpu::TextureFormat::Etc2Rgba8UnormSrgb),
        WGPUTextureFormat_EACR11Unorm => Some(wgpu::TextureFormat::EacR11Unorm),
        WGPUTextureFormat_EACR11Snorm => Some(wgpu::TextureFormat::EacR11Snorm),
        WGPUTextureFormat_EACRG11Unorm => Some(wgpu::TextureFormat::EacRg11Unorm),
        WGPUTextureFormat_EACRG11Snorm => Some(wgpu::TextureFormat::EacRg11Snorm),
        WGPUTextureFormat_ASTC4x4Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B4x4, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC4x4UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B4x4, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC5x4Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B5x4, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC5x4UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B5x4, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC5x5Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B5x5, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC5x5UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B5x5, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC6x5Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B6x5, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC6x5UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B6x5, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC6x6Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B6x6, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC6x6UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B6x6, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC8x5Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B8x5, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC8x5UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B8x5, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC8x6Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B8x6, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC8x6UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B8x6, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC8x8Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B8x8, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC8x8UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B8x8, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC10x5Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x5, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC10x5UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x5, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC10x6Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x6, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC10x6UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x6, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC10x8Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x8, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC10x8UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x8, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC10x10Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x10, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC10x10UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B10x10, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC12x10Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B12x10, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC12x10UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B12x10, channel: AstcChannel::UnormSrgb }),
        WGPUTextureFormat_ASTC12x12Unorm => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B12x12, channel: AstcChannel::Unorm }),
        WGPUTextureFormat_ASTC12x12UnormSrgb => Some(wgpu::TextureFormat::Astc { block: AstcBlock::B12x12, channel: AstcChannel::UnormSrgb }),
        _ => None,
    }
}

#[rustfmt::skip]
pub fn to_native_texture_format(rs_type: wgpu::TextureFormat) -> Option<WGPUTextureFormat> {
    use wgpu::{AstcBlock, AstcChannel};

    // TODO: unimplemented in wgpu-core
    // WGPUTextureFormat_Stencil8,
    // WGPUTextureFormat_Depth16Unorm

    match rs_type {
        // unimplemented in webgpu.h
        wgpu::TextureFormat::R16Unorm => None,
        wgpu::TextureFormat::R16Snorm => None,
        wgpu::TextureFormat::Rg16Unorm => None,
        wgpu::TextureFormat::Rg16Snorm => None,
        wgpu::TextureFormat::Rgba16Unorm => None,
        wgpu::TextureFormat::Rgba16Snorm => None,
        wgpu::TextureFormat::Astc { block:_, channel: AstcChannel::Hdr } => None,

        wgpu::TextureFormat::R8Unorm => Some(WGPUTextureFormat_R8Unorm),
        wgpu::TextureFormat::R8Snorm => Some(WGPUTextureFormat_R8Snorm),
        wgpu::TextureFormat::R8Uint => Some(WGPUTextureFormat_R8Uint),
        wgpu::TextureFormat::R8Sint => Some(WGPUTextureFormat_R8Sint),
        wgpu::TextureFormat::R16Uint => Some(WGPUTextureFormat_R16Uint),
        wgpu::TextureFormat::R16Sint => Some(WGPUTextureFormat_R16Sint),
        wgpu::TextureFormat::R16Float => Some(WGPUTextureFormat_R16Float),
        wgpu::TextureFormat::Rg8Unorm => Some(WGPUTextureFormat_RG8Unorm),
        wgpu::TextureFormat::Rg8Snorm => Some(WGPUTextureFormat_RG8Snorm),
        wgpu::TextureFormat::Rg8Uint => Some(WGPUTextureFormat_RG8Uint),
        wgpu::TextureFormat::Rg8Sint => Some(WGPUTextureFormat_RG8Sint),
        wgpu::TextureFormat::R32Float => Some(WGPUTextureFormat_R32Float),
        wgpu::TextureFormat::R32Uint => Some(WGPUTextureFormat_R32Uint),
        wgpu::TextureFormat::R32Sint => Some(WGPUTextureFormat_R32Sint),
        wgpu::TextureFormat::Rg16Uint => Some(WGPUTextureFormat_RG16Uint),
        wgpu::TextureFormat::Rg16Sint => Some(WGPUTextureFormat_RG16Sint),
        wgpu::TextureFormat::Rg16Float => Some(WGPUTextureFormat_RG16Float),
        wgpu::TextureFormat::Rgba8Unorm => Some(WGPUTextureFormat_RGBA8Unorm),
        wgpu::TextureFormat::Rgba8UnormSrgb => Some(WGPUTextureFormat_RGBA8UnormSrgb),
        wgpu::TextureFormat::Rgba8Snorm => Some(WGPUTextureFormat_RGBA8Snorm),
        wgpu::TextureFormat::Rgba8Uint => Some(WGPUTextureFormat_RGBA8Uint),
        wgpu::TextureFormat::Rgba8Sint => Some(WGPUTextureFormat_RGBA8Sint),
        wgpu::TextureFormat::Bgra8Unorm => Some(WGPUTextureFormat_BGRA8Unorm),
        wgpu::TextureFormat::Bgra8UnormSrgb => Some(WGPUTextureFormat_BGRA8UnormSrgb),
        wgpu::TextureFormat::Rgb10a2Unorm => Some(WGPUTextureFormat_RGB10A2Unorm),
        wgpu::TextureFormat::Rg11b10Float => Some(WGPUTextureFormat_RG11B10Ufloat),
        wgpu::TextureFormat::Rgb9e5Ufloat => Some(WGPUTextureFormat_RGB9E5Ufloat),
        wgpu::TextureFormat::Rg32Float => Some(WGPUTextureFormat_RG32Float),
        wgpu::TextureFormat::Rg32Uint => Some(WGPUTextureFormat_RG32Uint),
        wgpu::TextureFormat::Rg32Sint => Some(WGPUTextureFormat_RG32Sint),
        wgpu::TextureFormat::Rgba16Uint => Some(WGPUTextureFormat_RGBA16Uint),
        wgpu::TextureFormat::Rgba16Sint => Some(WGPUTextureFormat_RGBA16Sint),
        wgpu::TextureFormat::Rgba16Float => Some(WGPUTextureFormat_RGBA16Float),
        wgpu::TextureFormat::Rgba32Float => Some(WGPUTextureFormat_RGBA32Float),
        wgpu::TextureFormat::Rgba32Uint => Some(WGPUTextureFormat_RGBA32Uint),
        wgpu::TextureFormat::Rgba32Sint => Some(WGPUTextureFormat_RGBA32Sint),
        wgpu::TextureFormat::Stencil8 => Some(WGPUTextureFormat_Stencil8),
        wgpu::TextureFormat::Depth16Unorm => Some(WGPUTextureFormat_Depth16Unorm),
        wgpu::TextureFormat::Depth24Plus => Some(WGPUTextureFormat_Depth24Plus),
        wgpu::TextureFormat::Depth24PlusStencil8 => Some(WGPUTextureFormat_Depth24PlusStencil8),
        wgpu::TextureFormat::Depth32Float => Some(WGPUTextureFormat_Depth32Float),
        wgpu::TextureFormat::Depth32FloatStencil8 => Some(WGPUTextureFormat_Depth32FloatStencil8),
        wgpu::TextureFormat::Bc1RgbaUnorm => Some(WGPUTextureFormat_BC1RGBAUnorm),
        wgpu::TextureFormat::Bc1RgbaUnormSrgb => Some(WGPUTextureFormat_BC1RGBAUnormSrgb),
        wgpu::TextureFormat::Bc2RgbaUnorm => Some(WGPUTextureFormat_BC2RGBAUnorm),
        wgpu::TextureFormat::Bc2RgbaUnormSrgb => Some(WGPUTextureFormat_BC2RGBAUnormSrgb),
        wgpu::TextureFormat::Bc3RgbaUnorm => Some(WGPUTextureFormat_BC3RGBAUnorm),
        wgpu::TextureFormat::Bc3RgbaUnormSrgb => Some(WGPUTextureFormat_BC3RGBAUnormSrgb),
        wgpu::TextureFormat::Bc4RUnorm => Some(WGPUTextureFormat_BC4RUnorm),
        wgpu::TextureFormat::Bc4RSnorm => Some(WGPUTextureFormat_BC4RSnorm),
        wgpu::TextureFormat::Bc5RgUnorm => Some(WGPUTextureFormat_BC5RGUnorm),
        wgpu::TextureFormat::Bc5RgSnorm => Some(WGPUTextureFormat_BC5RGSnorm),
        wgpu::TextureFormat::Bc6hRgbUfloat => Some(WGPUTextureFormat_BC6HRGBUfloat),
        wgpu::TextureFormat::Bc6hRgbFloat => Some(WGPUTextureFormat_BC6HRGBFloat),
        wgpu::TextureFormat::Bc7RgbaUnorm => Some(WGPUTextureFormat_BC7RGBAUnorm),
        wgpu::TextureFormat::Bc7RgbaUnormSrgb => Some(WGPUTextureFormat_BC7RGBAUnormSrgb),
        wgpu::TextureFormat::Etc2Rgb8Unorm => Some(WGPUTextureFormat_ETC2RGB8Unorm),
        wgpu::TextureFormat::Etc2Rgb8UnormSrgb => Some(WGPUTextureFormat_ETC2RGB8UnormSrgb),
        wgpu::TextureFormat::Etc2Rgb8A1Unorm => Some(WGPUTextureFormat_ETC2RGB8A1Unorm),
        wgpu::TextureFormat::Etc2Rgb8A1UnormSrgb => Some(WGPUTextureFormat_ETC2RGB8A1UnormSrgb),
        wgpu::TextureFormat::Etc2Rgba8Unorm => Some(WGPUTextureFormat_ETC2RGBA8Unorm),
        wgpu::TextureFormat::Etc2Rgba8UnormSrgb => Some(WGPUTextureFormat_ETC2RGBA8UnormSrgb),
        wgpu::TextureFormat::EacR11Unorm => Some(WGPUTextureFormat_EACR11Unorm),
        wgpu::TextureFormat::EacR11Snorm => Some(WGPUTextureFormat_EACR11Snorm),
        wgpu::TextureFormat::EacRg11Unorm => Some(WGPUTextureFormat_EACRG11Unorm),
        wgpu::TextureFormat::EacRg11Snorm => Some(WGPUTextureFormat_EACRG11Snorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B4x4, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC4x4Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B4x4, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC4x4UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B5x4, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC5x4Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B5x4, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC5x4UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B5x5, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC5x5Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B5x5, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC5x5UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B6x5, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC6x5Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B6x5, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC6x5UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B6x6, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC6x6Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B6x6, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC6x6UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B8x5, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC8x5Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B8x5, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC8x5UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B8x6, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC8x6Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B8x6, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC8x6UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B8x8, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC8x8Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B8x8, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC8x8UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x5, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC10x5Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x5, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC10x5UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x6, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC10x6Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x6, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC10x6UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x8, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC10x8Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x8, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC10x8UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x10, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC10x10Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B10x10, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC10x10UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B12x10, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC12x10Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B12x10, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC12x10UnormSrgb),
        wgpu::TextureFormat::Astc { block: AstcBlock::B12x12, channel: AstcChannel::Unorm } => Some(WGPUTextureFormat_ASTC12x12Unorm),
        wgpu::TextureFormat::Astc { block: AstcBlock::B12x12, channel: AstcChannel::UnormSrgb } => Some(WGPUTextureFormat_ASTC12x12UnormSrgb),
    }
}
