name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install naga
        run: cargo install naga
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Install wasm-opt
        run: |
          curl -LO https://github.com/WebAssembly/binaryen/releases/download/version_118/binaryen-version_118-x86_64-linux.tar.gz
          tar -xvzf binaryen-version_118-x86_64-linux.tar.gz
          sudo mv binaryen-version_118/bin/wasm-opt /usr/local/bin/
      - name: Install Zig
        run: |
          curl -LO https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
          tar -xf zig-linux-x86_64-0.13.0.tar.xz
          sudo mv zig-linux-x86_64-0.13.0/zig /usr/local/bin/
      - name: Build demo app
        run: cd examples/zig/hi && bash build.sh
      - name: Install dependencies
        run: cd cana && npm install
      - name: Build the site
        run: cd cana && npm run build-split
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cana/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
