name: Build and Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/contextfreeinfo/taca-dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build demo app
        run: cd examples/zig/hi && bash build.sh
      - name: Build taca.js and demo page
        run: cd cana && npm install && npm run build-split
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cana/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
