name: Build and Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/contextfreeinfo/taca-dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build demo app
        run: cd examples/zig/hi && bash build.sh
      - name: Build taca.js and demo page
        run: cd cana && npm install && npm run build-split
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          destination_dir: demo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cana/dist
