[package]
name = "cana"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = "0.2.92"

[dependencies.naga]
version = "22.1.0"
default-features = false
features = ["glsl-out", "spv-in"]
